window.FUN_FACTS = [
  { topic: "news", label: "News", fact: "More Sales, Less Profit: The McDonald’s India Warning", why: "Westlife Foodworld's FY25 restaurant revenue rose 4%, yet annual profit fell. More sales did not automatically create more bottom-line value.", insight: "Track outlet contribution after food, labour, rent, discounts, delivery and marketing—not sales growth alone.", img: "./images/mcdonalds-india-margin-warning.jpg" },
  { topic: "news", label: "News", fact: "How KFC and Pizza Hut Improved Profit While Costs Increased", why: "Yum China's 2025 results show restaurant profit and margins improving through sales growth and operating efficiencies, even with higher delivery costs.", insight: "Cost pressure needs a system response: simplify work, improve throughput and protect the menu mix instead of making random cuts.", img: "./images/kfc-pizza-hut-cost-control.jpg" },
  { topic: "operations", label: "Operations", fact: "Protect Profitable Customers, Not Only High-Sales Customers", why: "A large bill can still carry heavy discounts, costly customisation, long table time or expensive delivery fees that reduce its real contribution.", insight: "Review contribution by customer channel and order type. Revenue is useful, but repeatable net profit deserves protection.", img: "./images/online-aggregator-commission.jpg" },
  { topic: "operations", label: "Operations", fact: "Supplier Rate Comparison Must Become a Daily System", why: "Rates, pack sizes, quality and availability can change quickly. An occasional comparison allows small purchasing leaks to continue unnoticed.", insight: "Maintain a daily rate sheet for priority items and compare like-for-like quality, yield, credit terms and delivery reliability.", img: "./images/delivery-demand-forecasting.jpg" },
  { topic: "costing", label: "Costing", fact: "The 0.73% Margin Warning", why: "On sales of ₹31,505, a gross profit of only ₹231 is approximately 0.73%. One small unplanned cost can erase the entire return.", insight: "Do not approve a sale on turnover alone. Check recipe cost, packaging, discount, tax and fulfilment cost before confirming the price.", img: "./images/portion-control-profit.jpg" },
  { topic: "costing", label: "Costing", fact: "Landing Cost Is More Than the Supplier’s Invoice Rate", why: "Freight, handling, tax treatment, breakage, trimming loss, storage and credit terms can make the lowest quoted rate the costlier purchase.", insight: "Compare suppliers on usable landed cost per unit, not invoice price. Buying decisions should reflect what finally reaches the plate.", img: "./images/central-kitchen-standardization.jpg" },
  { topic: "scaling", label: "Scaling", fact: "A Restaurant Website Should Be an Operational Tool", why: "A useful website can keep menus, hours, locations, reservations and direct-order paths accurate while reducing repeated guest questions.", insight: "Treat the website as a live service counter: assign ownership, update information quickly and measure enquiries, bookings and direct orders.", img: "./images/boba-bhai-qsr-expansion.jpg" },
  { topic: "scaling", label: "Scaling", fact: "Standardisation Must Come Before Expansion", why: "A second outlet multiplies unclear recipes, inconsistent training and purchasing gaps. Growth exposes weak systems rather than fixing them.", insight: "Document recipes, yields, service steps, checks and training first. Expand only when another team can repeat the same result.", img: "./images/olive-garden-india-expansion.jpg" },
  { topic: "hygiene", label: "Hygiene", fact: "A Cleaning Checklist Is Not a Complete Hygiene System", why: "A ticked sheet cannot confirm correct chemicals, dilution, contact time, food temperatures, handwashing or action on repeated failures.", insight: "Combine checklists with standards, training, records, verification and corrective action. Hygiene control needs evidence, not only signatures.", img: "./images/hygiene-audit-sop.jpg" }
];
window.WEEKLY_SPOTLIGHT = [
  { tag: "Luxury Hospitality", date: "July 2026", title: "Shinta Mani Mustang: Luxury Built Around Place", text: "Located above Jomsom in Nepal’s remote Mustang region, Shinta Mani Mustang is a 29-suite Himalayan retreat designed by renowned architect Bill Bensley. Surrounded by dramatic mountains and the ancient culture of the former Kingdom of Mustang, the property offers guests an exceptional sense of privacy, discovery and connection to its destination.<br><br>Its design draws inspiration from traditional Tibetan architecture while combining understated luxury with highly personalised service. Instead of depending only on expensive decoration, the hotel uses its natural surroundings, architecture, cultural identity and thoughtful hospitality to create a complete guest experience.<br><br>Carefully curated all-inclusive experiences introduce guests to local villages, ancient monasteries, remote landscapes, regional cuisine and Mustang’s distinctive cultural heritage. These experiences allow visitors to understand and connect with the destination rather than simply stay in a luxury room.<br><br>The hotel’s strength comes from the consistency of its complete hospitality concept. Its location, design, local culture, personalised service and meaningful guest experiences all communicate one connected story.<br><br>Shinta Mani Mustang was ranked No. 1 by Robb Report in its 50 Greatest Luxury Hotels on Earth 2026.", takeaway: "Luxury becomes distinctive when architecture, local culture, landscape and service tell one consistent story. Place should shape the guest journey, not remain a decorative theme.", img: "./images/shinta-mani-mustang-place.jpg" }
];
window.WA_PHONE = "919867378209";
window.WA_MESSAGE = "Hi, I saw your Hotel & QSR Operations Insights page. I want help with kitchen SOP / costing / workflow. Let's connect.";
